--------------------------------------------------------------------------------
-- cavlc_engine_tb.vhd
--
-- Self-checking testbench for cavlc_engine. Reads test vectors generated by
-- tools/gen_cavlc_vectors.c:
--
--   build/cavlc_vectors_in.txt  — one line per block:
--     <block_type> <n_coefs> <nC> <level_0> ... <level_15>
--
--   build/cavlc_vectors_out.txt — one line per block:
--     <bit_count> <hex_byte_0> <hex_byte_1> ...
--
-- For each vector: drives the cavlc_engine input, collects output bytes from
-- the bit_packer, and compares against the golden reference. After each block
-- the testbench sends a flush (in_last on the final vector) and verifies
-- byte-exact output.
--
-- Strategy: we process one block at a time. After driving the input, we flush
-- (via in_last='1' on a dummy beat or by tracking the bit_packer output).
-- Actually, we flush after EVERY block to capture the partial byte and compare
-- against the reference (which also byte-aligns after each block in the test
-- vector generator).
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library std;
use std.textio.all;
use std.env.all;

use work.cavlc_pkg.all;

entity cavlc_engine_tb is
    generic (
        IN_FILE  : string := "build/cavlc_vectors_in.txt";
        OUT_FILE : string := "build/cavlc_vectors_out.txt"
    );
end entity;

architecture sim of cavlc_engine_tb is

    constant CLK_PERIOD : time := 5 ns;

    signal clk     : std_logic := '0';
    signal rst_n   : std_logic := '0';

    signal in_valid : std_logic := '0';
    signal in_ready : std_logic;
    signal in_data  : level_packet_t;
    signal in_last  : std_logic := '0';

    signal out_valid : std_logic;
    signal out_ready : std_logic := '1';
    signal out_data  : unsigned(7 downto 0);
    signal out_last  : std_logic;

    signal test_done     : boolean := false;
    signal mismatch_count : natural := 0;
    signal vector_count   : natural := 0;

begin

    clk <= not clk after CLK_PERIOD / 2;

    rst_p : process
    begin
        rst_n <= '0';
        wait for 5 * CLK_PERIOD;
        wait until rising_edge(clk);
        rst_n <= '1';
        wait;
    end process;

    dut : entity work.cavlc_engine
        port map (
            clk       => clk,
            rst_n     => rst_n,
            in_valid  => in_valid,
            in_ready  => in_ready,
            in_data   => in_data,
            in_last   => in_last,
            out_valid => out_valid,
            out_ready => out_ready,
            out_data  => out_data,
            out_last  => out_last
        );

    --------------------------------------------------------------------------
    -- Main test process: drive inputs and check outputs one vector at a time
    --------------------------------------------------------------------------
    test_p : process
        file f_in   : text;
        file f_out  : text;
        variable L_in, L_out : line;
        variable open_status : file_open_status;

        variable v_bt      : integer;
        variable v_ncoefs  : integer;
        variable v_nC      : integer;
        variable v_level   : integer;
        variable v_bitcount : integer;
        variable v_byte_v  : unsigned(7 downto 0);

        -- Collected output bytes
        type byte_array_t is array (0 to 63) of unsigned(7 downto 0);
        variable got_bytes    : byte_array_t;
        variable got_count    : natural;
        variable exp_bytes    : byte_array_t;
        variable exp_count    : natural;
        variable exp_bitcount : natural;

        variable mc : natural := 0;
        variable vc : natural := 0;
    begin
        in_valid <= '0';
        in_last  <= '0';

        wait until rst_n = '1';
        wait until rising_edge(clk);

        file_open(open_status, f_in, IN_FILE, read_mode);
        assert open_status = open_ok
            report "Could not open " & IN_FILE severity failure;
        file_open(open_status, f_out, OUT_FILE, read_mode);
        assert open_status = open_ok
            report "Could not open " & OUT_FILE severity failure;

        report "Files opened, starting test..." severity note;

        while not endfile(f_in) loop
            -- Read input vector
            readline(f_in, L_in);
            read(L_in, v_bt);
            read(L_in, v_ncoefs);
            read(L_in, v_nC);

            in_data.block_type <= to_unsigned(v_bt, 3);
            in_data.n_coefs    <= to_unsigned(v_ncoefs, 5);
            -- nC: -1 sentinel maps to 31 (0x1F) for chroma DC
            if v_nC < 0 then
                in_data.nC <= to_unsigned(31, 5);
            else
                in_data.nC <= to_unsigned(v_nC, 5);
            end if;

            for k in 0 to 15 loop
                read(L_in, v_level);
                in_data.levels(k) <= to_signed(v_level, 16);
            end loop;

            -- Read expected output
            readline(f_out, L_out);
            read(L_out, v_bitcount);
            exp_bitcount := v_bitcount;
            exp_count := (v_bitcount + 7) / 8;
            for b in 0 to exp_count - 1 loop
                hread(L_out, v_byte_v);
                exp_bytes(b) := v_byte_v;
            end loop;

            -- Drive the packet with in_last='1' to flush after each block
            in_valid <= '1';
            in_last  <= '1';
            loop
                wait until rising_edge(clk);
                exit when in_ready = '1';
            end loop;
            in_valid <= '0';
            in_last  <= '0';

            -- Collect output bytes until out_last
            got_count := 0;
            if exp_count > 0 then
                loop
                    wait until rising_edge(clk);
                    if out_valid = '1' and out_ready = '1' then
                        got_bytes(got_count) := out_data;
                        got_count := got_count + 1;
                        exit when out_last = '1';
                    end if;
                    -- Timeout protection
                    if got_count > 63 then
                        report "Output overflow on vector " & integer'image(vc)
                            severity error;
                        exit;
                    end if;
                end loop;
            else
                -- Zero-bit block: wait for flush to complete (no bytes expected)
                -- Just wait a few cycles for the engine to finish
                for w in 0 to 20 loop
                    wait until rising_edge(clk);
                    exit when out_last = '1' and out_valid = '1';
                end loop;
            end if;

            -- Compare
            if got_count /= exp_count then
                mc := mc + 1;
                report "Vector " & integer'image(vc) &
                       ": byte count mismatch, expected " &
                       integer'image(exp_count) & " got " &
                       integer'image(got_count)
                    severity error;
            else
                for b in 0 to exp_count - 1 loop
                    if got_bytes(b) /= exp_bytes(b) then
                        mc := mc + 1;
                        report "Vector " & integer'image(vc) &
                               " byte " & integer'image(b) &
                               ": expected " & integer'image(to_integer(exp_bytes(b))) &
                               " got " & integer'image(to_integer(got_bytes(b)))
                            severity error;
                    end if;
                end loop;
            end if;

            vc := vc + 1;

            -- Progress report every 100 vectors
            if vc mod 100 = 0 then
                report "Progress: vector " & integer'image(vc) &
                       " at " & time'image(now) severity note;
            end if;

            -- Small gap between vectors
            wait until rising_edge(clk);
            wait until rising_edge(clk);
        end loop;

        file_close(f_in);
        file_close(f_out);

        mismatch_count <= mc;
        vector_count   <= vc;
        test_done      <= true;
        wait;
    end process;

    --------------------------------------------------------------------------
    -- Finalizer
    --------------------------------------------------------------------------
    final_p : process
    begin
        wait until test_done;
        wait for 10 * CLK_PERIOD;
        if mismatch_count = 0 then
            report "CAVLC ENGINE PASS - " & integer'image(vector_count) &
                   " vectors verified" severity note;
        else
            report "CAVLC ENGINE FAIL - " & integer'image(mismatch_count) &
                   " mismatches over " & integer'image(vector_count) & " vectors"
                severity failure;
        end if;
        std.env.finish;
        wait;
    end process;

    --------------------------------------------------------------------------
    -- Watchdog
    --------------------------------------------------------------------------
    watchdog_p : process
    begin
        wait for 50 ms;
        report "Watchdog timeout" severity failure;
        std.env.finish;
        wait;
    end process;

end architecture;
