--------------------------------------------------------------------------------
-- transform_engine_tb.vhd
--
-- Self-checking testbench for transform_engine. Reads golden vectors
-- generated by tools/gen_transform_vectors.c:
--
--   build/transform_vectors.txt
--
-- Vector format (one test per three lines):
--   M <mode>                        -- 0..5
--   I <v0> <v1> ... <v15>           -- input  (decimal signed 32-bit)
--   O <v0> <v1> ... <v15>           -- expected output (decimal signed 32-bit)
--
-- The testbench drives each vector into the DUT, waits one cycle for the
-- registered output, and compares every element. Reports PASS/FAIL at end.
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library std;
use std.textio.all;
use std.env.all;

entity transform_engine_tb is
    generic (
        VEC_FILE : string := "build/transform_vectors.txt"
    );
end entity;

architecture sim of transform_engine_tb is

    constant CLK_PERIOD : time := 5 ns;

    signal clk   : std_logic := '0';
    signal rst_n : std_logic := '0';

    signal mode_i  : unsigned(2 downto 0) := (others => '0');
    signal valid_i : std_logic := '0';
    signal ready_o : std_logic;
    signal valid_o : std_logic;
    signal ready_i : std_logic := '1';

    type block_t is array (0 to 15) of signed(31 downto 0);
    signal din  : block_t := (others => (others => '0'));
    signal dout : block_t;

    signal test_count     : natural := 0;
    signal mismatch_count : natural := 0;
    signal done           : boolean := false;

    function mode_name(m : integer) return string is
    begin
        case m is
            when 0 => return "dct4x4";
            when 1 => return "idct4x4";
            when 2 => return "hadamard4x4";
            when 3 => return "ihadamard4x4";
            when 4 => return "hadamard2x2";
            when 5 => return "ihadamard2x2";
            when others => return "UNKNOWN";
        end case;
    end function;

begin

    clk <= not clk after CLK_PERIOD / 2;

    rst_p : process
    begin
        rst_n <= '0';
        wait for 5 * CLK_PERIOD;
        wait until rising_edge(clk);
        rst_n <= '1';
        wait;
    end process;

    --------------------------------------------------------------------
    -- DUT instantiation
    --------------------------------------------------------------------
    dut : entity work.transform_engine
        port map (
            clk     => clk,
            rst_n   => rst_n,
            mode_i  => mode_i,
            din_0   => din(0),   din_1   => din(1),
            din_2   => din(2),   din_3   => din(3),
            din_4   => din(4),   din_5   => din(5),
            din_6   => din(6),   din_7   => din(7),
            din_8   => din(8),   din_9   => din(9),
            din_10  => din(10),  din_11  => din(11),
            din_12  => din(12),  din_13  => din(13),
            din_14  => din(14),  din_15  => din(15),
            valid_i => valid_i,
            ready_o => ready_o,
            dout_0  => dout(0),  dout_1  => dout(1),
            dout_2  => dout(2),  dout_3  => dout(3),
            dout_4  => dout(4),  dout_5  => dout(5),
            dout_6  => dout(6),  dout_7  => dout(7),
            dout_8  => dout(8),  dout_9  => dout(9),
            dout_10 => dout(10), dout_11 => dout(11),
            dout_12 => dout(12), dout_13 => dout(13),
            dout_14 => dout(14), dout_15 => dout(15),
            valid_o => valid_o,
            ready_i => ready_i
        );

    --------------------------------------------------------------------
    -- Main driver: read vectors, push into DUT, check output.
    --------------------------------------------------------------------
    stim_p : process
        file     vec_f  : text;
        variable L      : line;
        variable tag    : character;
        variable mode_v : integer;
        variable val    : integer;
        variable din_v  : block_t;
        variable exp_v  : block_t;
        variable open_status : file_open_status;
        variable tc     : natural := 0;
        variable mc     : natural := 0;
        variable elem_count : integer;
    begin
        valid_i <= '0';
        wait until rst_n = '1';
        wait until rising_edge(clk);

        file_open(open_status, vec_f, VEC_FILE, read_mode);
        assert open_status = open_ok
            report "could not open " & VEC_FILE
            severity failure;

        while not endfile(vec_f) loop
            -- Read M line
            readline(vec_f, L);
            if L'length = 0 then next; end if;
            read(L, tag);
            assert tag = 'M'
                report "expected 'M' tag, got '" & tag & "'"
                severity failure;
            read(L, mode_v);

            -- Read I line
            assert not endfile(vec_f) report "unexpected EOF after M line" severity failure;
            readline(vec_f, L);
            read(L, tag);
            assert tag = 'I'
                report "expected 'I' tag, got '" & tag & "'"
                severity failure;
            for i in 0 to 15 loop
                read(L, val);
                din_v(i) := to_signed(val, 32);
            end loop;

            -- Read O line
            assert not endfile(vec_f) report "unexpected EOF after I line" severity failure;
            readline(vec_f, L);
            read(L, tag);
            assert tag = 'O'
                report "expected 'O' tag, got '" & tag & "'"
                severity failure;
            for i in 0 to 15 loop
                read(L, val);
                exp_v(i) := to_signed(val, 32);
            end loop;

            -- Drive input
            mode_i <= to_unsigned(mode_v, 3);
            din    <= din_v;
            valid_i <= '1';

            -- Wait for accept
            loop
                wait until rising_edge(clk);
                exit when ready_o = '1';
            end loop;
            valid_i <= '0';

            -- Wait for output valid
            loop
                wait until rising_edge(clk);
                exit when valid_o = '1';
            end loop;

            -- Compare
            if mode_v >= 4 then
                elem_count := 4;
            else
                elem_count := 16;
            end if;

            for i in 0 to elem_count - 1 loop
                if dout(i) /= exp_v(i) then
                    mc := mc + 1;
                    report "MISMATCH test " & integer'image(tc) &
                           " (" & mode_name(mode_v) & ")" &
                           " elem " & integer'image(i) &
                           ": expected " & integer'image(to_integer(exp_v(i))) &
                           ", got " & integer'image(to_integer(dout(i)))
                        severity error;
                end if;
            end loop;

            tc := tc + 1;
        end loop;

        file_close(vec_f);

        test_count     <= tc;
        mismatch_count <= mc;
        done           <= true;
        wait;
    end process;

    --------------------------------------------------------------------
    -- Finalizer
    --------------------------------------------------------------------
    final_p : process
    begin
        wait until done;
        wait for 2 * CLK_PERIOD;
        if mismatch_count = 0 then
            report "PASS - " & integer'image(test_count) &
                   " transform tests verified"
                severity note;
        else
            report "FAIL - " & integer'image(mismatch_count) &
                   " mismatches over " & integer'image(test_count) & " tests"
                severity failure;
        end if;
        std.env.finish;
        wait;
    end process;

    watchdog_p : process
    begin
        wait for 5 ms;
        report "watchdog timeout - test did not complete" severity failure;
        std.env.finish;
        wait;
    end process;

end architecture;
