/* gen_line_buffer_vectors.c — golden vectors for the VHDL line_buffer,
 * generated by driving the HLS line_buffer_t (src/hls/line_buffer.c)
 * through two short frames of random reconstructions. Writes
 * build/line_buffer_vectors.txt, one command per line:
 *   S <mbs_w>                         frame start (also sets the width)
 *   R                                 MB row start (not before row 0)
 *   F <c> <at> <al> <atl> <atr> <top_y x16> <tr_y x4> <tl_y> <left_y x16>
 *       <top_u x8> <top_v x8> <tl_u> <tl_v> <left_u x8> <left_v x8>
 *       <nc_y_top x4> <nc_y_left x4> <nc_u_top x2> <nc_u_left x2>
 *       <nc_v_top x2> <nc_v_left x2> <mode4_top x4> <mode4_left x4>
 *   C <c> <y_bot x16> <uv_bot x16> <y_right x16> <uv_right x16>
 *       <nc_y x16> <nc_u x4> <nc_v x4> <mode4 x16>
 * Samples that are unavailable are printed as 0 and not compared.
 */
#include "types.h"
#include "line_buffer.h"
#include <stdio.h>
#include <string.h>

static line_buffer_t lb;
static unsigned rng_state = 0x1B0FFEE1;
static unsigned xorshift32(void)
{
    unsigned x = rng_state;
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    rng_state = x;
    return x;
}

static void put_arr(FILE *f, const u8 *a, int n) { for (int i = 0; i < n; i++) fprintf(f, " %d", a[i]); }

int main(void)
{
    FILE *f = fopen("build/line_buffer_vectors.txt", "w");
    if (!f) { perror("build/line_buffer_vectors.txt"); return 1; }
    int nf = 0, nc_ = 0;
    for (int frame = 0; frame < 2; frame++) {
        int mbs_w = (frame == 0) ? 6 : 4;
        int rows  = 3;
        lb_init(&lb, mbs_w * 16);
        fprintf(f, "S %d\n", mbs_w);
        for (int r = 0; r < rows; r++) {
            if (r > 0) { lb_begin_mb_row(&lb); fprintf(f, "R\n"); }
            for (int c = 0; c < mbs_w; c++) {
                u8 top[16] = {0}, left[16] = {0}, tl = 0;
                u8 tu[8] = {0}, lu[8] = {0}, tlu = 0, tv[8] = {0}, lv[8] = {0}, tlv = 0;
                int at, al, atl, at2, al2, atl2;
                lb_gather_luma_16x16(&lb, c, top, left, &tl, &at, &al, &atl);
                lb_gather_chroma_8x8(&lb, c, tu, lu, &tlu, tv, lv, &tlv, &at2, &al2, &atl2);
                int atr = lb.top_valid && (c < mbs_w - 1);
                u8 tr[4] = {0};
                if (atr) for (int j = 0; j < 4; j++) tr[j] = lb.buf_y[lb.top_idx][(c + 1) * 16 + j];
                u8 ncyt[4], ncyl[4], ncut[2], ncul[2], ncvt[2], ncvl[2], m4t[4], m4l[4];
                int lv_ok = (c > 0) && lb.left_valid;
                for (int k = 0; k < 4; k++) {
                    ncyt[k] = (u8)lb_nc_y_top(&lb, c * 4 + k);
                    ncyl[k] = lv_ok ? lb.nc_y_left[k] : 0;
                    m4t[k]  = (u8)lb_mode4_y_top(&lb, c * 4 + k);
                    m4l[k]  = lv_ok ? lb.mode4_y_left[k] : 2;
                }
                for (int k = 0; k < 2; k++) {
                    ncut[k] = (u8)lb_nc_u_top(&lb, c * 2 + k);
                    ncvt[k] = (u8)lb_nc_v_top(&lb, c * 2 + k);
                    ncul[k] = lv_ok ? lb.nc_u_left[k] : 0;
                    ncvl[k] = lv_ok ? lb.nc_v_left[k] : 0;
                }
                fprintf(f, "F %d %d %d %d %d", c, at, al, atl, atr);
                put_arr(f, top, 16); put_arr(f, tr, 4); fprintf(f, " %d", tl); put_arr(f, left, 16);
                put_arr(f, tu, 8); put_arr(f, tv, 8); fprintf(f, " %d %d", tlu, tlv);
                put_arr(f, lu, 8); put_arr(f, lv, 8);
                put_arr(f, ncyt, 4); put_arr(f, ncyl, 4); put_arr(f, ncut, 2); put_arr(f, ncul, 2);
                put_arr(f, ncvt, 2); put_arr(f, ncvl, 2); put_arr(f, m4t, 4); put_arr(f, m4l, 4);
                fprintf(f, "\n");
                nf++;

                /* random reconstruction and CAVLC state for this MB */
                u8 ry[256], ruv[128], ncy[16], ncu[4], ncv[4], m4[16];
                for (int i = 0; i < 256; i++) ry[i]  = (u8)(xorshift32() & 255);
                for (int i = 0; i < 128; i++) ruv[i] = (u8)(xorshift32() & 255);
                for (int i = 0; i < 16; i++)  { ncy[i] = (u8)(xorshift32() % 17); m4[i] = (u8)(xorshift32() % 9); }
                for (int i = 0; i < 4; i++)   { ncu[i] = (u8)(xorshift32() % 17); ncv[i] = (u8)(xorshift32() % 17); }
                lb_commit_recon(&lb, c, ry, ruv);
                lb_commit_nc(&lb, c, ncy, ncu, ncv, m4);
                u8 ybot[16], uvbot[16], yright[16], uvright[16];
                for (int j = 0; j < 16; j++) { ybot[j] = ry[15 * 16 + j]; uvbot[j] = ruv[7 * 16 + j]; yright[j] = ry[j * 16 + 15]; }
                for (int rr = 0; rr < 8; rr++) { uvright[2 * rr] = ruv[rr * 16 + 14]; uvright[2 * rr + 1] = ruv[rr * 16 + 15]; }
                fprintf(f, "C %d", c);
                put_arr(f, ybot, 16); put_arr(f, uvbot, 16); put_arr(f, yright, 16); put_arr(f, uvright, 16);
                put_arr(f, ncy, 16); put_arr(f, ncu, 4); put_arr(f, ncv, 4); put_arr(f, m4, 16);
                fprintf(f, "\n");
                nc_++;
            }
        }
    }
    fclose(f);
    printf("wrote %d fetches, %d commits to build/line_buffer_vectors.txt\n", nf, nc_);
    return 0;
}
