#!/usr/bin/env python3
"""Emit the L4 test vectors as C arrays to link into the Vitis application.

The board needs the same two artifacts the RTL testbench uses: the input
frame, and the payload the C reference says the kernel must produce. Linking
them in removes file I/O from the first hardware run, which is the point --
the first run should be testing the kernel and nothing else.

Usage:
  gen_board_vectors.py <frame.yuv> <payload.txt> <outdir>

Writes <outdir>/frame_data.c and <outdir>/golden_data.c, plus golden.bin for
anything that would rather read a file.
"""
import os
import sys


def emit(path, name, data):
    with open(path, "w") as f:
        f.write("/* Generated by tools/gen_board_vectors.py. Do not edit. */\n")
        f.write("const unsigned char %s[] = {\n" % name)
        for i in range(0, len(data), 16):
            f.write("    " + ",".join("0x%02X" % b for b in data[i:i + 16]) + ",\n")
        f.write("};\n")
        f.write("const unsigned int %s_len = %d;\n" % (name, len(data)))
    print("wrote %s (%d bytes)" % (path, len(data)))


def main():
    if len(sys.argv) != 4:
        print(__doc__)
        return 1
    yuv_path, payload_path, outdir = sys.argv[1], sys.argv[2], sys.argv[3]
    os.makedirs(outdir, exist_ok=True)

    with open(yuv_path, "rb") as f:
        frame = f.read()

    # DCC_DUMP_SLICE writes one decimal byte per line.
    with open(payload_path) as f:
        payload = bytes(int(line) for line in f if line.strip())

    emit(os.path.join(outdir, "frame_data.c"), "frame_nv12", frame)
    emit(os.path.join(outdir, "golden_data.c"), "golden_payload", payload)
    with open(os.path.join(outdir, "golden.bin"), "wb") as f:
        f.write(payload)
    print("wrote %s" % os.path.join(outdir, "golden.bin"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
